### PR TITLE
fix warnings

### LINKED ISSUE #76: Uninitialized string offset & Undefined array key
While testing some cf validation, I stumbled upon these warnings:

```
Warning: Uninitialized string offset 13 in /myproject/vendor/davidepastore/codice-fiscale/src/AbstractCalculator.php on line 155

Warning: Undefined array key "" in /myproject/vendor/davidepastore/codice-fiscale/src/AbstractCalculator.php on line 156

Warning: Uninitialized string offset 14 in /myproject/vendor/davidepastore/codice-fiscale/src/AbstractCalculator.php on line 155

Warning: Undefined array key "" in /myproject/vendor/davidepastore/codice-fiscale/src/AbstractCalculator.php on line 156
```

This is similar to issue #36 but IMHO is more serious, because in this case it doesn't depend on any mistaken arguments.

I can propose a PR, which is by the way as simple as:

```diff
<             $k = $temporaryCodiceFiscale[$i];
<             $sum = $sum + $dictionaryArray[$k];
---
>             $k = $temporaryCodiceFiscale[$i] ?? '';
>             $sum += $dictionaryArray[$k] ?? 0;

```

### PR DESCRIPTION
**Pull request by garak**
Fix #76

### CODE REVIEW

**Comment by DavidePastore** [comment]
Hi @garak. Could you please also include some tests for it?

**Comment by garak** [comment]
I just added a test case (and cleaned up tests a bit).
I realized it was my fault in the end, so the case is the same as the other issue I mentioned in mine.
The current test is passing without warnings. If you run the same test on master, you'll get the warnings instead.

The problem, at this point, is that the calculator calculates an invalid cf when passing a shorter belfiore code. The problem is present in master branch too. Let met know if you prefer to merge this PR and wait for a different PR fixing this other problem, or if it's better to fix everything here

**Comment by DavidePastore** [comment]
Thanks for your PR, @garak. Let's have this fix in another PR.

File: test/InverseCalculatorTest.php [hunk 1]
```diff
@@ -29,234 +29,239 @@ public function testInverseCalculate($codiceFiscale, $omocodiaAllowed, $century,
         $this->assertEquals(null, $actual->getSurname());
     }
 
+    public function todotestInverseCalculatorDoesNotThrowWarnings(): void
```
Comment (DavidePastore) [inline test/InverseCalculatorTest.php]: Is the name of the function correct?

**Review by DavidePastore — CHANGES_REQUESTED** [review]
I left a little comment

File: test/InverseCalculatorTest.php (hunk 1 above)
Comment (garak) [reply test/InverseCalculatorTest.php]: My bad, I renamed it

**Review by DavidePastore — APPROVED** [review]

**Review by DavidePastore — APPROVED** [review]
